#
#Mon Apr 13 10:49:42 PET 2026
goog\:chromeOptions={args\=[--incognito, --start-maximized, --disable-notifications, --no-sandbox, --disable-dev-shm-usage, --incognito, --start-maximized, --disable-notifications, --no-sandbox, --disable-dev-shm-usage, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
